[build]
  publish = "."
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  # Define secrets in Netlify dashboard (Site settings → Environment variables):
  # GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO, GITHUB_BRANCH, COINAPI_KEY

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
